CREATE TABLESPACE tbs1
 DATAFILE 'tbsp1_datafile1' SIZE 1M;

 CREATE TABLESPACE tbs2
 DATAFILE 'tbsp2_datafile1' SIZE 1M;





 ALTER USER ash200042123 QUOTA 1m ON tbs1;





ALTER TABLE STUDENT
DROP PRIMARY KEY;


ALTER TABLE DEPARTMENT
DROP PRIMARY KEY;

DROP TABLE STUDENT;
DROP TABLE DEPARTMENT;



 CREATE TABLE DEPARTMENT(
    name VARCHAR2(100) PRIMARY KEY,
    id INT 
) TABLESPACE tbs1 ;

 CREATE TABLE STUDENT(
    name VARCHAR2(100) PRIMARY KEY,
    id INT ,
    dept VARCHAR2 (100),
    CONSTRAINT fk_dept FOREIGN KEY (dept) REFERENCES DEPARTMENT(name)
) TABLESPACE tbs1 ;





CREATE TABLE COURSE
( 
    code VARCHAR(100),
    name VARCHAR(100),
    credit VARCHAR(100),
    offer_by VARCHAR(100),
    CONSTRAINT pk_course PRIMARY KEY (code),
    CONSTRAINT FK_COURSE FOREIGN KEY (offer_by) REFERENCES DEPARTMENT(name)
) TABLESPACE tbs2;







INSERT INTO DEPARTMENT VALUES ('CSE', '3');
INSERT INTO DEPARTMENT VALUES ('EEE', '1');
INSERT INTO DEPARTMENT VALUES ('MPE', '5');


INSERT INTO STUDENT VALUES ('ANNA', '101', 'EEE');
INSERT INTO STUDENT VALUES ('BOB', '102', 'CSE');
INSERT INTO STUDENT VALUES ('C', '103', 'MPE');
INSERT INTO STUDENT VALUES ('D', '104', 'CSE');
INSERT INTO STUDENT VALUES ('E', '105', 'EEE');
INSERT INTO STUDENT VALUES ('F', '106', 'MPE');
INSERT INTO STUDENT VALUES ('G', '107', 'CSE');
INSERT INTO STUDENT VALUES ('H', '108', 'MPE');









SELECT tablespace_name , bytes /1024/1024 MB
FROM dba_free_space
WHERE tablespace_name ='TBS1';









ALTER TABLESPACE tbs1
ADD DATAFILE 'tbsp1_datafile1.dbf'
SIZE 2m
AUTOEXTEND ON;


ALTER DATABASE
DATAFILE 'tbsp2_datafile1.dbf' RESIZE 10m;












SELECT tablespace_name , bytes /1024/1024 MB
FROM dba_free_space
WHERE tablespace_name ='TBS1';


SELECT tablespace_name , bytes /1024/1024 MB
FROM dba_free_space
WHERE tablespace_name ='TBS2';








DROP TABLESPACE tbs1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE tbs2
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

